language: go

go:
- "1.12"

env:
- GO111MODULE=on

notifications:
  email:
    on_success: never
    on_failure: always

matrix:
  # It's ok if our code fails on unstable development versions of Go.
  allow_failures:
  - go: develop
  # Don't wait for tip tests to finish. Mark the test run green if the
  # tests pass on the stable versions of Go.
  fast_finish: true
cache:
  directories:
  - $GOPATH/pkg
  - $GOPATH/bin

before_install:
- go get golang.org/x/tools/cmd/cover
- go get github.com/mattn/goveralls

script:
- go test -v ./... -covermode=count -coverprofile=coverage.out
- $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci